# Generated by Django 5.1.7 on 2025-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learningpath_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstep',
            name='max_mistakes',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='learningstep',
            name='step_type',
            field=models.CharField(choices=[('vocabulary', 'Kelime Öğrenme'), ('matching', 'Eşleştirme'), ('multiple_choice', 'Çoktan Seçmeli'), ('writing', 'Yazma'), ('listening', 'Dinleme'), ('final_quiz', 'Final Quiz'), ('treasure', 'Hazine')], max_length=20),
        ),
    ]
