# Generated by Django 5.1.7 on 2025-05-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_learningstep_max_mistakes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mongo_id',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
    ]
