# Generated by Django 5.1.7 on 2025-05-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_mongo_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('word_hunt', 'Kelime Avı'), ('word_puzzle', 'Kelime Yapbozu'), ('speed_quiz', 'Hızlı Quiz')], max_length=20)),
                ('best_score', models.IntegerField(default=0)),
                ('date_achieved', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_type')},
            },
        ),
    ]
